export enum KeysDictionaryEnum {
  AUTHORIZATION_REQUIRED = "AUTHORIZATION_REQUIRED",
  PROCESSING_DATA_CLIENT_ERROR = "PROCESSING_DATA_CLIENT_ERROR",
  TEXT_FEELING_SERVICE_ERROR = "TEXT_FEELING_SERVICE_ERROR",
  SOME_PARAMETERS_ARE_MISSING = "SOME_PARAMETERS_ARE_MISSING",
  SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG",
  NOT_VALID_EMAIL = "NOT_VALID_EMAIL",
  NUMBER_GREATER_THAN = "NUMBER_GREATER_THAN",
  MUST_BE_EVEN_NUMBER = "MUST_BE_EVEN_NUMBER",
};

export type LocalMessageDictionary = { [key in keyof typeof KeysDictionaryEnum]: string };
