module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  coverageDirectory: "coverage",
  modulePathIgnorePatterns: [
    "./src/mapper-tsk/package.json",
    "./src/mapper-tsk/package-lock.json",
    "./src/mapper-tsk/tsconfig.json",
    "./src/resources-tsk/package.json",
    "./src/resources-tsk/package-lock.json",
    "./src/resources-tsk/test/locals/",
    "./src/resources-tsk/test/locals/resources",
    "./src/resources-tsk/tsconfig.json",
    "./src/result-tsk/package.json",
    "./src/result-tsk/package-lock.json",
    "./src/result-tsk/test/resultCodes.json",
    "./src/result-tsk/tsconfig.json",
    "./src/validator-tsk/package.json",
    "./src/validator-tsk/package-lock.json",
    "./src/validator-tsk/tsconfig.json",
  ],
};
